title: "FIXME title"
description: "FIXME, description"
url: https://c128128.github.io/JekyllTest/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - package.json

collections:
  articles:
    output: true
    permalink: /en/articles/:name